<a href="https://colab.research.google.com/github/DavoodSZ1993/OpenCV_Tutorial/blob/main/01_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
type(my_list)

list

* `np.array()`: creates an array

In [3]:
my_list = np.array(my_list)
type(my_list)

numpy.ndarray

* `numpy.arange(start, end, step)`: Return evenly spaced values within a given interval.

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

* `numpy.zeros(shape)`: Return a new array of given shape and type, filled with zeros.

In [6]:
np.zeros(shape=(5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

* `numpy.ones(shape)`: Return an array of given shape and type, filled with ones.

In [7]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* `np.random.seed(seed=None)`: Reseed the Singleton RandomState instance. In other words, makes random numbers predictable.

In [8]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [9]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

With the seed reset (every time), the same set of numbers will appear every time. If the random seed is not reset, different numbers appear with every invocation. 

In [10]:
np.random.rand(4)

array([0.4236548 , 0.64589411, 0.43758721, 0.891773  ])

In [11]:
np.random.rand(4)

array([0.96366276, 0.38344152, 0.79172504, 0.52889492])

* `np.random.rand(shape)`: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].
* `np.random.randint(low, high=None, size=None)`: Return random integers from low (inclusive) or high (exclusive).

In [12]:
np.random.seed(101)
array = np.random.randint(0, 100, 10)
array

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

* `np.ndarray.max()`: Return the maximum along the given axis.

In [13]:
array.max()

95